Database Design pull request
jumpegg/theCompanyOfGod-test pull request #11
Opened 2017-06-23 10:02 UTC by jumpegg

테이블 설계 및 생성
- 테이블 생성을 위한 sql 파일 작성
- 주석 추가 작업

요청사항 반영
- user_id, post_id PK추가
- is_del 데이터형 변경 및 주석 정렬

2017-06-23 10:18 UTC, rokoroku reviewed
PR을 닫고 새로 여시기보다는, 기존 PR에 이어나가시는 것을 추천해 드려요.

2017-06-23 10:18 UTC, rokoroku commented on theCOG.sql
> +  `is_del` tinyint(2) NOT NULL DEFAULT '0',   -- 삭제유뮤
tinyint의 default가 '0' (character 값)이어도 문제가 없었나요?
tinyint의 크기를 2로 설정하신 이유도 궁금해요.

2017-06-23 10:28 UTC, jumpegg commented on theCOG.sql
> +  `is_del` tinyint(2) NOT NULL DEFAULT '0',   -- 삭제유뮤
아 아직 PR 사용법이 미숙해서 새로 만들어야하는줄 알았습니다. 
tinyint 0일 경우의 문제점에 대해서는 저도 잘 모르겟습니다. 
실 활용은 해본적이 없거든요
그리고 tinyint 사이즈 2는 딱히 이유가 있어서 정한 사이즈는 아닙니다. 
웹에서 tinyint 사이즈 1과 2 논란이 있기는 하던데 저는 그냥 데이터에 여유를 두고싶어서 
사이즈를 2로 한것이구요.
혹시 권장되는 데이터형이 있으면 알려주시면 반영하겟습니다

2017-06-23 11:24 UTC, dcoun requested changes

2017-06-23 11:24 UTC, dcoun commented on theCOG.sql
> +  `id` int(11) NOT NULL,                    -- 인덱스(PK)
id가 딱히 필요없어보입니다.

2017-06-23 11:30 UTC, jumpegg commented on theCOG.sql
> +  `id` int(11) NOT NULL,                    -- 인덱스(PK)
넵 삭제하겟습니다

2017-06-23 12:05 UTC, rokoroku commented on theCOG.sql
> +  `is_del` tinyint(2) NOT NULL DEFAULT '0',   -- 삭제유뮤
저도 tinyint에 '0'을 설정해도 되는지 궁금해서 질문드린 거라, 직접 한 번 알아보고 결과를 공유해주시면 좋겠네요! 

그리고 tinyint 사이즈 1과 2에 대한 논란도 알려주시면 좋을 것 같아요 :)

2017-06-23 12:16 UTC, jumpegg commented on theCOG.sql
> +  `is_del` tinyint(2) NOT NULL DEFAULT '0',   -- 삭제유뮤
네넵 찾아보겟습니다

2017-06-26 03:45 UTC, dcoun approved these changes

2017-06-26 03:46 UTC, jumpegg commented
1. tinyint(1) 과 tinyint(2) 의 차이점이 1일 경우 0 이상의 값들은 다 1로 처리해서 코드성 데이터를 다룰수가 없다는 글을 봣었는데 실제로 값을 집어넣어보니 10 이상의 값들도 들어가서 잘못된 예제를 본거 같습니다.
그리고 is_del 은 boolean 형으로 쓸 것이기 때문에 tinyint(1) 이 맞는것 같아 고쳣습니다.

2. default '0' 을 설정해놓으면 해당 컬럼에 숫자형 0 이 들어가는것 같습니다. 그리고 character 형 '0' 은 들어가지 않는것을 확인했습니다.

3. like 테이블에 id를 삭제했습니다

2017-06-26 03:51 UTC, rokoroku approved these changes
고생하셨습니다 😄 

모두가 PR을 수락(Approve)하였기 때문에, 이제 PR을 master로 직접 merge하시면 됩니다.

이번 PR을 통해 GitHub를 통해 협업한다는 것이 어떤 느낌인지 알게 되셨으리라 생각하고, 앞으로 남은 마일스톤들도 이번 PR처럼 진행해 주시면 되겠습니다. 😃 

- 2번 문항에 대한 코멘트:   
`default '0'` 형태를 제대로 받을 수 있다고 해도,  
데이터 자료형 일관성이나 가독성을 위해서도 `default 0`으로 작성하시는 편이 더 좋을 것 같아요 :)

2017-06-26 03:58 UTC, jumpegg commented
네넵 깃헙 쓰는 방식을 배울 수 있어서 좋네요 ㅋㅋ

master merge 후에 계속 진행하겟습니다~!

2017-06-26 04:02 UTC, merged